/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Your
 */
public class Votacao extends javax.swing.JFrame {

    /** Creates new form Votacao */
    public Votacao() {
        initComponents();
        btnCandidato1.setEnabled(false);
        btnCandidato2.setEnabled(false); /////////////////////////////AQUI
        btnCandidato3.setEnabled(false);
        btnApurar.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCandidato1 = new javax.swing.JButton();
        btnCandidato2 = new javax.swing.JButton();
        btnCandidato3 = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnApurar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCandidato1.setText("Candidato 1");
        btnCandidato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandidato1ActionPerformed(evt);
            }
        });

        btnCandidato2.setText("Candidato 2");
        btnCandidato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandidato2ActionPerformed(evt);
            }
        });

        btnCandidato3.setText("Candidato 3");
        btnCandidato3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandidato3ActionPerformed(evt);
            }
        });

        btnIniciar.setText("Iniciar Votação");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Fim Votação");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnApurar.setText("Apuração...");
        btnApurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApurarActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        lblResultado.setText("Resultado:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnCandidato1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCandidato2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCandidato3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFinalizar)
                                .addGap(50, 50, 50)
                                .addComponent(btnApurar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCandidato2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCandidato3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCandidato1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApurar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
         int votoCandidato1= 0;
         int votoCandidato2 =0;
         int votoCandidato3 =0;
        String r;
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed

        btnApurar.setEnabled(false);
        btnCandidato1.setEnabled(true);
        btnCandidato2.setEnabled(true); 
        btnCandidato3.setEnabled(true);
  //      btnIniciar.setEnabled(false);
        Limpar();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed

        btnCandidato1.setEnabled(false);
        btnCandidato2.setEnabled(false); 
        btnCandidato3.setEnabled(false);
        btnApurar.setEnabled(true);
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnApurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApurarActionPerformed

        btnCandidato1.setEnabled(false);
        btnCandidato2.setEnabled(false); 
        btnCandidato3.setEnabled(false);       
        btnIniciar.setEnabled(true);
        btnIniciar.setText("Iniciar Nova Votação");
        
    if (( votoCandidato1 > votoCandidato3) &&  ( votoCandidato1 > votoCandidato2)) {
	//r= ("Candidato1 ganhou com: " +votoCandidato1+ " votos");
        r= ("Candidato1 ganhou. ");
	}
	else  if (( votoCandidato2 > votoCandidato1) &&  ( votoCandidato2 > votoCandidato3)) { 
	//r= ("Candidato2 ganhou com: " +votoCandidato2+ " votos");
        r= ("Candidato2 ganhou. ");
	} 
	else  if (( votoCandidato3 > votoCandidato1) &&  ( votoCandidato3 > votoCandidato2)) { 
	//r= ("Candidato3 ganhou com: " +votoCandidato3+ " votos");
        r= ("Candidato3 ganhou. ");
	} 	                          
	else  {
	r= ("Eleição cancelada, EMPATE ");
	}

          lblResultado.setText(r+"VOTOS: " + "Cad1: " + votoCandidato1 + ", Cad2: " + votoCandidato2+ ", Cad3: " + votoCandidato3);
       //   System.out.println("Resultado: " +"votoCandidato1: "+votoCandidato1+", votoCandidato2: "+votoCandidato2+", votoCandidato3:"+votoCandidato3);
         
    }//GEN-LAST:event_btnApurarActionPerformed

    private void btnCandidato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidato1ActionPerformed
                 
                        votoCandidato1= votoCandidato1+1;
                        
    }//GEN-LAST:event_btnCandidato1ActionPerformed

    private void btnCandidato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidato2ActionPerformed

                        votoCandidato2= votoCandidato2+1;
    }//GEN-LAST:event_btnCandidato2ActionPerformed

    private void btnCandidato3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidato3ActionPerformed

                         votoCandidato3= votoCandidato3+1;
    }//GEN-LAST:event_btnCandidato3ActionPerformed
        public void Limpar()
        {
         votoCandidato1=0;
         votoCandidato2=0;
         votoCandidato3=0; 
         lblResultado.setText("Resultado: ");
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Votacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Votacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Votacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Votacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Votacao().setVisible(true);
                           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApurar;
    private javax.swing.JButton btnCandidato1;
    private javax.swing.JButton btnCandidato2;
    private javax.swing.JButton btnCandidato3;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables

}
